events { worker_connections 1024; }

http {
    resolver 8.8.8.8 1.1.1.1 valid=300s;
    resolver_timeout 5s;

    server {
        listen 10000;

        location / {
            # Consente il corretto inoltro dei flussi streaming dinamici (M3U8, MP4, ecc.)
            proxy_pass $http_x_target_url; 
            proxy_set_header Host $proxy_host;
            
            # Ottimizzazioni cruciali per i video: disattiva il buffering per evitare scatti
            proxy_buffering off;
            proxy_set_header Connection "keep-alive";
            
            # Supporto fondamentale per l'avanzamento rapido (Seek) nei lettori video
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;
            proxy_store off;
        }
    }
}
